---

configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_sudoers: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5


homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - cmake
  - ninja
  - gperf
  - python3
  - ccache
  - qemu
  - dtc
  - mas
  - bitwarden-cli
  - vim

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-file-transfer
  - atom
  - bbedit
  - bitwarden
  - coconutbattery
  - devdocs
  - discord
  - docker
  - drawio
  - expressvpn
  - firefox
  - gcc-arm-embedded
  - google-chrome
  - google-earth-pro
  - kindle
  - microsoft-excel
  - microsoft-powerpoint
  - microsoft-word
  - microsoft-teams
  - microsoft-remote-desktop
  - mqtt-explorer
  - netspot
  - plex
  - plexamp
  - quicken
  - raspberry-pi-imager
  - slack
  - secure-pipes
  - sweet-home3d
  - transfer
  - transmission
  - vlc
  - wireshark
  - xbar
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1153157709, name: "Speedtest" }

mas_email: "kumar.gala@gmail.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
