---

configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_sudoers: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Maps
  - FaceTime
  - News
  - Keynote
  - Numbers
  - Pages
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 2
  - name: "Mail"
    path: "/System/Applications/Mail.app"
    pos: 3
  - name: "Music"
    path: "/System/Applications/Music.app"
    pos: 4
  - name: "Notes"
    path: "/System/Applications/Notes.app"
    pos: 5
  - name: "Stickies"
    path: "/System/Applications/Stickies.app"
    pos: 6
  - name: "Calendar"
    path: "/System/Applications/Calendar.app"
    pos: 7
  - name: "Discord"
    path: "/Applications/Discord.app"
    pos: 8
  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 9
  - name: "Safari"
    path: "/System/Applications/Safari.app"
    pos: 10
  - name: "Calculator"
    path: "/System/Applications/Calculator.app"
    pos: 11
  - name: "BBEdit"
    path: "/Applications/BBEdit.app"
    pos: 12
  - name: "System Preferences"
    path: "/System/Applications/System Preferences.app"
    pos: 13
  - name: "Dictionary"
    path: "/System/Applications/Dictionary.app"
    pos: 14
  - name: "Contacts"
    path: "/System/Applications/Contacts.app"
    pos: 15
  - name: "Reminders"
    path: "/System/Applications/Reminders.app"
    pos: 16
  - name: "Photos"
    path: "/System/Applications/Photos.app"
    pos: 17
  - name: "Activity Monitor"
    path: "/System/Applications/Utilities/Activity Monitor.app"
    pos: 18
  - name: "Terminal"
    path: "/System/Applications/Utilities/Terminal.app"
    pos: 19
  - name: "Messages"
    path: "/System/Applications/Messages.app"
    pos: 20
  - name: "App Store"
    path: "/System/Applications/App Store.app"
    pos: 21

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - cmake
  - ninja
  - gperf
  - python3
  - ccache
  - qemu
  - dtc
  - mas
  - bitwarden-cli
  - vim
  - git
  - wget
  - awscli
  - cscope
  - dfu-util
  - esptool
  - platformio
  - mitmproxy
  - nmap
  - telnet
  - tmux
  - iperf3
  - speedtest-cli
  - jq
  - sphinx-doc
  - bpytop
  - osx-cpu-temp
  - chezmoi
# Used by sdk-ng builds
  - autoconf
  - automake
  - bash
  - binutils
  - gawk
  - gnu-sed
  - gnu-tar
  - help2man
  - ncurses
  - pkg-config
  - makeself

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-file-transfer
  - atom
  - bbedit
  - bitwarden
  - coconutbattery
  - devdocs
  - discord
  - docker
  - drawio
  - expressvpn
  - firefox
  - gcc-arm-embedded
  - google-chrome
  - chrome-remote-desktop-host
  - google-drive
  - google-earth-pro
  - grandperspective
  - irccloud
  - kindle
  - microsoft-excel
  - microsoft-powerpoint
  - microsoft-word
  - microsoft-teams
  - microsoft-remote-desktop
  - monitorcontrol
  - mqtt-explorer
  - netspot
  - onyx
  - packet-peeper
  - plex
  - plexamp
  - quicken
  - raspberry-pi-imager
  - slack
  - serial
  - secure-pipes
  - send-to-kindle
  - sweet-home3d
  - transfer
  - transmission
  - vlc
  - wireshark
  - xbar
  - xquartz
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1408727408, name: "com.adriangranados.wifiexplorerlite" }
  - { id: 1494760882, name: "Bluefruit Connect" }
  - { id: 557428110,  name: "LightBlue" }
  - { id: 1336679524, name: "BlueSee" }
  - { id: 1348795218, name: "TeraTime" }
  - { id: 1153157709, name: "Speedtest" }
  - { id: 1509085044, name: "Bluetooth Inspector" }
  - { id: 418357707,  name: "CocoaPacketAnalyzer" }

mas_email: "kumar.gala@gmail.com"
mas_password: ""

# iOS apps installed - MAS doesn't support yet
#    itemId = 1472272574	Big Ass Fans.app
#    itemId = 787415770		Enlighten.app
#    itemId = 902021647		Haiku by BAF.app
#    itemId = 1456074307	Linkind.app
#    itemId = 1501617838	Span.app
#    itemId = 998509713		kumo cloud.app
#    itemId = 440464115		myAudi.app
#    itemId = 920820854		myLink.app

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
